version: '3'

services:
  postgres:
    image: postgres:13.3-alpine3.14
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=${DB_USERNAME}
      - APP_DB_PASS=${DB_PASSWORD}
      - APP_DB_NAME=${DB_NAME}
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080